FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine AS base
USER app
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/csharp/api/api.csproj", "src/csharp/api/"]
RUN dotnet restore "src/csharp/api/api.csproj" -r linux-musl-x64
COPY . .
WORKDIR "/src/src/csharp/api"
RUN dotnet publish "api.csproj" -c $BUILD_CONFIGURATION -r linux-musl-x64 --self-contained true /p:PublishSingleFile=true -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime-deps:10.0-alpine AS final
WORKDIR /app
COPY --from=build /app/publish .
RUN rm -f appsettings.Development.json
ENTRYPOINT ["./api"]
